Oświetlenie:
  oswietlenie.kuchnia : Oświetlenie w kuchni
  oswietlenie.salon : Oświetlenie salonu
  oswietlenie.garaz : Oświetlenie garażu
Ogrzewanie:
  ogrzewanie.kuchnia : Grzejnik w kuchni
Wentylacja:
  wentylacja.kuchnia1 : Wentylator 1 w kuchni
  wentylacja.kuchnia2 : Wentylator 2 w kuchni